package com.mogujie.tt.DB.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table GroupUser.
 */
public class GroupUserEntity {

    private Long id;
    private long peerId;
    /** Not-null value. */
    private String userName;
    /** Not-null value. */
    private String nickName;
    /** Not-null value. */
    private String userIcon;
    /** Not-null value. */
    private String signature;
    /** Not-null value. */
    private String intro;
    /** Not-null value. */
    private String gender;
    private int createTime;
    private int joinTime;
    /** Not-null value. */
    private String role;
    /** Not-null value. */
    private String joinType;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public GroupUserEntity() {
    }

    public GroupUserEntity(Long id) {
        this.id = id;
    }

    public GroupUserEntity(Long id, long peerId, String userName, String nickName, String userIcon, String signature, String intro, String gender, int createTime, int joinTime, String role, String joinType) {
        this.id = id;
        this.peerId = peerId;
        this.userName = userName;
        this.nickName = nickName;
        this.userIcon = userIcon;
        this.signature = signature;
        this.intro = intro;
        this.gender = gender;
        this.createTime = createTime;
        this.joinTime = joinTime;
        this.role = role;
        this.joinType = joinType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getPeerId() {
        return peerId;
    }

    public void setPeerId(long peerId) {
        this.peerId = peerId;
    }

    /** Not-null value. */
    public String getUserName() {
        return userName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /** Not-null value. */
    public String getNickName() {
        return nickName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /** Not-null value. */
    public String getUserIcon() {
        return userIcon;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserIcon(String userIcon) {
        this.userIcon = userIcon;
    }

    /** Not-null value. */
    public String getSignature() {
        return signature;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSignature(String signature) {
        this.signature = signature;
    }

    /** Not-null value. */
    public String getIntro() {
        return intro;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIntro(String intro) {
        this.intro = intro;
    }

    /** Not-null value. */
    public String getGender() {
        return gender;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGender(String gender) {
        this.gender = gender;
    }

    public int getCreateTime() {
        return createTime;
    }

    public void setCreateTime(int createTime) {
        this.createTime = createTime;
    }

    public int getJoinTime() {
        return joinTime;
    }

    public void setJoinTime(int joinTime) {
        this.joinTime = joinTime;
    }

    /** Not-null value. */
    public String getRole() {
        return role;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRole(String role) {
        this.role = role;
    }

    /** Not-null value. */
    public String getJoinType() {
        return joinType;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setJoinType(String joinType) {
        this.joinType = joinType;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
